// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nareshit.proxy;

public interface GeoIPServiceSoap extends java.rmi.Remote {
    public com.nareshit.proxy.GeoIP getGeoIP(java.lang.String IPAddress) throws 
         java.rmi.RemoteException;
    public com.nareshit.proxy.GeoIP getGeoIPContext() throws 
         java.rmi.RemoteException;
}
